In [10]:
from PIL import Image
import numpy as np
from sklearn.cluster import KMeans

In [56]:
clusterCount = 48
imageName = 'image13-small'

image = Image.open('images/' + imageName + '.jpg')
imageArray = np.asarray(image)

imageHeight = imageArray.shape[0]
imageWidth = imageArray.shape[1]

print(imageArray)

[[[215 219 222]
  [214 218 221]
  [214 218 221]
  ...
  [220 223 228]
  [218 221 226]
  [217 220 225]]

 [[215 219 222]
  [214 218 221]
  [214 218 221]
  ...
  [218 221 226]
  [218 221 226]
  [218 221 226]]

 [[215 219 222]
  [214 218 221]
  [213 217 220]
  ...
  [217 220 225]
  [218 221 226]
  [218 221 226]]

 ...

 [[178 159 152]
  [166 147 140]
  [156 139 131]
  ...
  [106 104  91]
  [ 80  78  65]
  [ 61  59  46]]

 [[188 168 161]
  [184 165 158]
  [179 161 151]
  ...
  [ 99  97  84]
  [ 88  86  73]
  [ 75  73  60]]

 [[163 143 134]
  [171 151 142]
  [173 155 145]
  ...
  [103 101  88]
  [ 97  95  82]
  [103 101  88]]]


In [57]:
originalArrayShape = np.array([imageHeight, imageWidth, 3])
flatArrayShape = np.array([imageHeight * imageWidth, 3])
imageFlatArray = np.reshape(imageArray, flatArrayShape)

imageFlatArray.shape

(1635840, 3)

In [58]:
kmeanModel = KMeans(n_clusters=clusterCount, n_jobs=4).fit(imageFlatArray)

In [59]:
clusteredImageArray = kmeanModel.predict(imageFlatArray)

clusteredImageArray

array([ 6,  6,  6, ..., 13, 13, 13], dtype=int32)

In [60]:
kmeanModel.cluster_centers_

array([[119.71527685, 119.50860574, 111.53879253],
       [202.29851811, 203.20134321, 206.02941992],
       [ 63.82516697,  40.6558895 ,  28.33533698],
       [ 25.03489373,  23.92893794,  27.56388831],
       [181.48984881, 152.46973842, 127.17293017],
       [ 84.45815264,  84.32970188,  76.57670631],
       [217.53008847, 219.35219595, 223.24379309],
       [103.59991905,  92.23557704,  65.31765042],
       [136.65264285, 122.53285561, 102.42773243],
       [ 48.56588691,  52.0527653 ,  59.91442293],
       [173.16038614, 171.53750872, 168.26988835],
       [ 41.00285182,  42.84482312,  45.98957081],
       [ 83.60786773,  54.45579628,  38.58031167],
       [ 95.55098354,  94.7492774 ,  85.01132075],
       [ 65.48265152,  67.59367671,  57.09036167],
       [160.00791271, 144.29547726, 125.14009662],
       [ 90.55064077,  81.2896816 ,  57.28941736],
       [210.53141927, 213.24184515, 216.57076118],
       [132.96983943,  90.84500217,  66.21083466],
       [ 44.12591484,  28.25357

In [61]:
encodedImageFlatArray = np.zeros(flatArrayShape)

In [62]:
for pixelIdx in range(len(clusteredImageArray)):
    clusterIdx = clusteredImageArray[pixelIdx]
    encodedImageFlatArray[pixelIdx] = kmeanModel.cluster_centers_[clusterIdx]

In [63]:
encodedImageArray = np.reshape(encodedImageFlatArray, originalArrayShape)
encodedImageArray.shape

(1280, 1278, 3)

In [64]:
encodedImage = Image.fromarray(encodedImageArray.astype(np.uint8))

encodedImage.save('output/' + imageName + '-' + str(clusterCount) + '.jpg')